#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Verificamos apenas o 'tr', que é o comando que usaremos agora
    _check_dependencies "tr"
    _display_wait_box
    input_files=$(_get_files "par_type=all")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box ""
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local dir=""
    local filename=""

    dir=$(dirname -- "$input_file")
    filename=$(basename -- "$input_file")

    # Remove apenas números (0-9) do nome do arquivo
    output_file=$(tr -d '[:digit:]' <<<"$filename")
    
    _check_output "$?" "$output_file" "$input_file" "" || return 1

    # Se o nome original era só números, o resultado será vazio. 
    # Nesses casos, o script ignora para não renomear para um arquivo "sem nome".
    if [[ -z "$output_file" ]]; then
        return 1
    fi

    # Executa a renomeação
    _move_file "skip" "$input_file" "$dir/$output_file" || return 1
}

_main "$@"
